### ISSUE TITLE
Location of libGR

### ISSUE THREAD

**Issue by Chris00** [mseri/ocaml-gr#8]
The environment variable `GRDIR` is supposed to be pointing to the directory where the [tarball](https://gr-framework.org/c.html#installation) is unpacked.  Thus the correct library location relative to `GRDIR` is `/lib/libGR.so`.

**Comment by Chris00** [comment]
P.S. `LIBGRPATH` is confusing as it is *not* the directory to the library (as for `LD_LIBRARY_PATH`) but the path including the library filename.

**Comment by mseri** [comment]
Good points. I am going to fix them on the fly! Thanks
